### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by DafterCola** [auwaho/steam-order-scanner#1]
Hello,

i tried this couple of times but i can't get it to work. When i start scanning it scans for like 10 minutes and "start scan" comes up again but nothing happens. I wonder if it has something to do with the amount of buy orders i have (375)? I have disabled every other extension, but still this is not working.

I would love to use this.

Google Chrome Version 80.0.3987.87 (Official Build) (64-bit)

**Comment by auwaho** [comment]
Hello. Any console logs after "Start scan"?

**Comment by DafterCola** [comment]
After five minutes it gives only these errors https://imgur.com/a/nE6p60Y

Only thing that happens is that "My Buy Orders" goes orange after i press start scan.

**Comment by auwaho** [comment]
My Buy Orders button goes orange when scan is started and it goes white again when it ends.
Based on errors you have microban from Steam for spamming steam community market, it's temprary.
Have you tried to open any of these error links in console? These are the items pages of your orders

**Comment by auwaho** [comment]
> Have you tried to open any of these error links in console? These are the items pages of your orders

If page looks something like this, so it's definitely Steam error (limitation) for spamming.
![image](https://user-images.githubusercontent.com/47985643/74263087-d06a6e80-4d06-11ea-997a-d3ca7f6dea13.png)

**Comment by DafterCola** [comment]
Now there was not any error messages:
▼ single scan start ▼ scanner.js:153  
■  single scan end  ■ 

Same as before "My Buy Orders" goes orange and after the scan white, but nothing else appears.
Btw, should i start to see results in orders while scanning is happening or just after the scan?

**Comment by auwaho** [comment]
You should see your orders changing colors to green or orange during scan.

**Comment by auwaho** [comment]
And after scan if there any links (without errors) between "▼ single scan start ▼" and "■ single scan end ■", these are overpriced orders.

**Comment by DafterCola** [comment]
Okay weird that nothing happens.. I tried the last scan with my laptop but results are the same as my main computer. Any ideas what should i try?

**Comment by auwaho** [comment]
Does the background color of your orders change to something like this? 
![image](https://user-images.githubusercontent.com/47985643/74266480-0a3e7380-4d0d-11ea-9700-2f5f72c7b91d.png)

If yes, so extension works properly.
If no, so take a look at your extensions page, are there any error links under SLS extension?

**Comment by DafterCola** [comment]
No color changes at all, i have used steam inventory helper backup version for sell listings and market history helper and they have changed colors just like that. I have disabled them for now.

No error links for SLS and everything is allowed for SLS

**Comment by DafterCola** [comment]
i also checked SLS folder and every file is modified in 30-jan-20 4:47PM so it should be newest version?

i appreciate your replies thank you.

**Comment by auwaho** [comment]
You welcome. Yes this is the newest. 
In what currency is your wallet btw??

**Comment by DafterCola** [comment]
Euros

**Comment by auwaho** [comment]
Okay, I'll check it as soon as I can, maybe this is the problem. Wait for reply.

**Comment by DafterCola** [comment]
Thank you, take your time i have to go to work now. I will have time again tomorrow to test this.

**Comment by auwaho** [comment]
So, let's figure out that the problem is actually in getting prices. Help me so I can help you.
[SLS.zip](https://github.com/auwaho/SteamListingsScanner/files/4195250/SLS.zip)
Here is the test variant of extension that shows prices in console while scan. 
I need you to start scan, wait some time, save log or make screenshot whatever and 
send it here.

**Comment by DafterCola** [comment]
Here is my log [log.log](https://github.com/auwaho/SteamListingsScanner/files/4198890/log.log)

**Comment by auwaho** [comment]
Very strange that you don't getting item prices without any error in the console.
Since I haven't euro wallet account It would take much more time to figure out the problem.

**Comment by DafterCola** [comment]
I understand. Only clue seems to be that it has maybe something to do with the currency, i don't know if this helps but it seems that the number of my currency in steam is "3" and converted currency id on item listing page is 2003. Also with Euro prices the € sign is after the amount like "26.90€" instead of like in dollar prices before digits ($26.90). If you have any questions how my pages look like, i can give you more inside look. I also understand if this is too much time taking problem to solve. We all have our own projects.

Btw this problem got me interested in JavaScript so much that i started learning java with "Mimo: Learn to Code" app two days ago. 

`
var g_bLoggedIn = true;
var g_rgWalletInfo = {"wallet_currency":3,"wallet_country":"FI","wallet_state":"","wallet_fee":"1","wallet_fee_minimum":"1","wallet_fee_percent":"0.05","wallet_publisher_fee_percent_default":"0.10","wallet_fee_base":"0","wallet_balance":"xxxx","wallet_delayed_balance":"0","wallet_max_balance":"175000","wallet_trade_max_balance":"157500","success":1,"rwgrsn":-2};
var g_strCountryCode = "FI";
var g_strLanguage = "english";
`

`converted_currencyid":2003`"

**Comment by DafterCola** [comment]
I deleted my last 2 messages because errors came from my own edited files lol.. Here is what i get when i try to debug original
![2nd debug](https://user-images.githubusercontent.com/60852852/74601506-d87c3280-50a7-11ea-9456-0dc396a8ab9c.png)

![2nd debug2](https://user-images.githubusercontent.com/60852852/74601622-d1095900-50a8-11ea-91a5-a26a15a19b73.png)

**Comment by Pultset** [comment]
![1st debug2](https://user-images.githubusercontent.com/60852852/74601053-22621a00-50a2-11ea-89c5-2efe6a767092.png)

**Comment by auwaho** [comment]
Sorry for not responding that long, was busy a bit. 
Tell me, do you scan items with open lots (for example, CSGO weapons) or with hidden ones, with a table view (for example, CSGO cases)?

**Comment by DafterCola** [comment]
No problem, has been kinda fun trying to figure this out myself. I mostly try to collect profile backgrounds and emoticons. Some items even have less than 5 sell and buy offers.

**Comment by auwaho** [comment]
Ok, we found a problem. And it is not in the currency.
At first I could not understand why this is not working. But your answers and last debug result pushed me on what I totally forgot. 
Initially I made this extension to scan items with open lots, so as I needed. Trully I didn't even think about items without lots (like yours: backgrounds, emoticons etc.). The problem is that the extension gets these lots' prices on the item page. On the background, emoticon etc. pages there are no these prices but the table.

**Comment by auwaho** [comment]
It seems that I got extra work in my free time. 😃
I will redo this feature and publish the update after a while.
Thanks for helping me improve my little project!

**Comment by DafterCola** [comment]
> It seems that I got extra work in my free time. 
> I will redo this feature and publish the update after a while.
> Thanks for helping me improve my little project!

You are genius! Happy to help and also i have learned thing or two about JavaScript, so this has been great training for me. No need to rush, take it easy.

**Comment by auwaho** [comment]
Bug fixed, update released.
